# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
                ('key', models.BigIntegerField()),
                ('cover_url', models.CharField(max_length=300)),
                ('cover', models.ImageField(upload_to='qdmm')),
                ('intro', models.TextField()),
                ('catalog', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
                ('total_hit', models.CharField(max_length=50)),
                ('total_recmd', models.CharField(max_length=20)),
                ('month_hit', models.CharField(max_length=20)),
                ('month_recmd', models.CharField(max_length=20)),
                ('week_hit', models.CharField(max_length=20)),
                ('week_recmd', models.CharField(max_length=20)),
                ('word_count', models.CharField(max_length=50)),
                ('chapter_info', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('added_time', models.DateTimeField()),
            ],
        ),
    ]
