# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='cover',
            field=models.ImageField(upload_to='media'),
        ),
    ]
